name: Test checkmysite against TYPO3 11

on: [pull_request]

jobs:
  CGL:
    name: Coding Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s composer -e 'validate'

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s composerInstall

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s lint

      - name: Validate code against CGL
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s cgl -n
